In [1]:
import pandas as pd

In [6]:
df = pd.read_csv('trainFeatures42k.csv', header=None)

In [15]:
df

0           1           2           3           4           5   \
0       1  538.267964 -314.023125  443.809967  470.780028  176.561668   
1       0 -238.730010  224.609513 -197.464121   23.557813 -219.122649   
2       1   51.647165  -27.271305 -185.258708  -50.103687  216.830344   
3       4  110.890600   62.854265  -97.528878  -21.291295  297.976619   
4       0 -300.296735  152.547221  -91.949199   90.416744 -453.385929   
...    ..         ...         ...         ...         ...         ...   
41995   0 -345.093292   11.065646 -174.747451  326.644346 -579.877065   
41996   1   98.457753 -141.147284  -62.981609   14.906726  237.202744   
41997   7 -277.428469   15.614291  -57.528770 -361.782458  176.541830   
41998   6 -264.146701 -242.806686 -715.897321  -53.385171  275.870094   
41999   9  154.825322 -173.127245 -246.767154  375.123163   99.948838   

               6           7           8           9   ...          51  \
0     -336.130920   23.221391  -45.523748 -232.436917  ...  -90.463868   
1     -223.695514 -172.689736  125.561839 -194.150108  ...   44.464226   
2     -207.152351   60.301310   95.431402 -117.051561  ...  -12.722596   
3      -32.899732   34.647964  -85.574818  -60.120835  ...   23.112458   
4      -89.195463  -15.051828  -38.036779 -190.363654  ...  -28.107534   
...           ...         ...         ...         ...  ...         ...   
41995  -56.739589  284.803065 -168.864051 -222.675505  ...  253.792926   
41996 -249.597505  194.935575   50.475505 -103.460750  ...    6.134738   
41997 -602.188100  161.762741 -126.375074  171.504748  ...    6.213266   
41998   21.959704  136.165956  370.284019 -103.682699  ... -191.564370   
41999 -167.474902  304.429111  150.721373   75.111694  ...  262.355344   

               52          53          54          55          56          57  \
0      107.934027   25.417533  -97.235438  -66.589588   22.468479 -111.476083   
1       -7.825244   -5.260700   18.905444    9.593545  -40.015688  -96.469679   
2       -3.039582  -26.963181  -18.563280   16.095458  -81.075489  -42.589100   
3      -62.558569 -115.846264  -16.405413  -37.548852 -269.649782 -130.725868   
4       30.400739  -47.075128  -13.092383  -85.371052 -141.450375  -36.200100   
...           ...         ...         ...         ...         ...         ...   
41995   -2.276109  -76.423324   16.421357  -47.923449 -164.135483  -41.600881   
41996   14.508979  -14.115238  -14.021636   59.891608  -30.775038  -10.648890   
41997 -108.696850 -337.164756 -122.304109  146.981833  -73.174110  124.840056   
41998 -343.088713    6.490805   70.169534   31.228294   32.430615  -93.090557   
41999   22.579378   99.904137   52.142862 -154.116176  -17.805026   53.552108   

               58          59          60  
0       62.807185   74.771969   -7.480156  
1       24.317962 -137.943930   94.025390  
2       52.083444  -29.080312   42.344233  
3      -23.526366  -20.448849   37.234782  
4      114.188444  -21.988893  -46.480710  
...           ...         ...         ...  
41995   58.991670  -82.371978 -254.698814  
41996   22.862916  -28.956328  -35.001724  
41997 -183.646347  -63.447742  -52.520125  
41998  -34.462157  -97.924401  -33.647373  
41999   61.658479    7.398493  100.638849  

[42000 rows x 61 columns]

In [17]:
y = df.iloc[:,0]
X = df.iloc[:, 1:]

In [18]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif

In [21]:
test = SelectKBest(f_classif, 10).fit(X,y)

/Users/nobo/opt/anaconda3/envs/machine-learning/lib/python3.7/site-packages/sklearn/utils/validation.py:71: FutureWarning: Pass k=10 as keyword args. From version 0.25 passing these as positional arguments will result in an error
  FutureWarning)


In [27]:
test.scores_

array([2727.84071479,  661.03781658, 3513.78269035, 1531.02017789,
       2499.19141844,  640.43222549, 2026.54178503,  920.90030684,
        189.16824767,  250.55007773,  549.04730885, 1026.78326963,
        533.07603378,  203.81489328,   85.73645882,  162.07948899,
         70.55310658,   41.61379432,  187.71000978,  371.25365123,
       5450.2527223 , 2593.97597916, 2225.8826568 ,  738.50636537,
        384.69337687,  453.97024243,  505.5004999 ,  556.98727323,
        368.63825742,  541.40170462,  503.31892127,  275.75858114,
        146.66244437,  241.56821558,  337.48758858,  209.28721033,
        144.23890606,   41.90125572,   51.97332786,  171.43781305,
       5876.48838944, 6797.7975934 , 3127.13272254,  983.69052847,
       1600.96578499,  686.30807919,  940.05809942,  398.38828413,
        601.19695425,  504.50192119,  230.58756653, 1026.18011691,
        506.64876912,  273.85351297,   58.35658538,  153.61500767,
        288.57462493,  215.26092033,  216.24924742,  106.48443

In [31]:
test.scores_

array([2727.84071479,  661.03781658, 3513.78269035, 1531.02017789,
       2499.19141844,  640.43222549, 2026.54178503,  920.90030684,
        189.16824767,  250.55007773,  549.04730885, 1026.78326963,
        533.07603378,  203.81489328,   85.73645882,  162.07948899,
         70.55310658,   41.61379432,  187.71000978,  371.25365123,
       5450.2527223 , 2593.97597916, 2225.8826568 ,  738.50636537,
        384.69337687,  453.97024243,  505.5004999 ,  556.98727323,
        368.63825742,  541.40170462,  503.31892127,  275.75858114,
        146.66244437,  241.56821558,  337.48758858,  209.28721033,
        144.23890606,   41.90125572,   51.97332786,  171.43781305,
       5876.48838944, 6797.7975934 , 3127.13272254,  983.69052847,
       1600.96578499,  686.30807919,  940.05809942,  398.38828413,
        601.19695425,  504.50192119,  230.58756653, 1026.18011691,
        506.64876912,  273.85351297,   58.35658538,  153.61500767,
        288.57462493,  215.26092033,  216.24924742,  106.48443

In [34]:
test.get_support(indices=True)

array([ 0,  2,  4,  6, 20, 21, 22, 40, 41, 42])

In [45]:
X_new = test.transform(X)

In [46]:
from sklearn.preprocessing import normalize

In [47]:
X_new = normalize(X_new)

In [50]:
class_data_1=X_new[y==1]

In [55]:
import numpy as np
from scipy.stats import chi2
def mahalanobis_method(class_data):
    x_minus_mu = class_data - np.mean(class_data, axis=0) 
    cov = np.cov(x_minus_mu.T)
    inv_covmat = np.linalg.inv(cov)
    left_term = np.dot(x_minus_mu, inv_covmat)
    mahal = np.dot(left_term, x_minus_mu.T)
    md = np.sqrt(mahal.diagonal())
    outlier = []
    C = np.sqrt(chi2.ppf((1-0.01), df=class_data.shape[1])) 
    for index, value in enumerate(md):
        if value > C:
            outlier.append(index)
        else:
            continue 
    return outlier, md

In [70]:
ol, md = mahalanobis_method(class_data_1)

In [74]:
t=[2,5,2,5,4]
t.sort(reverse=True)
t

[5, 5, 4, 2, 2]

In [80]:
len(class_data_1)

4684

In [81]:
len(ol)

311

In [86]:
np.ones(len(class_data_1)) * 4

array([4., 4., 4., ..., 4., 4., 4.])

In [83]:
set(range(len(class_data_1)))

{0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [68]:
ol.sort()

In [69]:
ol

[10,
 11,
 23,
 61,
 77,
 90,
 103,
 169,
 170,
 185,
 187,
 199,
 205,
 213,
 214,
 258,
 264,
 275,
 315,
 415,
 417,
 422,
 489,
 517,
 523,
 529,
 547,
 553,
 554,
 558,
 575,
 604,
 608,
 612,
 617,
 652,
 681,
 686,
 713,
 716,
 724,
 725,
 735,
 766,
 770,
 793,
 803,
 807,
 821,
 827,
 860,
 866,
 892,
 897,
 904,
 917,
 919,
 949,
 970,
 980,
 982,
 988,
 996,
 1005,
 1009,
 1063,
 1071,
 1105,
 1106,
 1139,
 1171,
 1174,
 1216,
 1222,
 1265,
 1266,
 1324,
 1365,
 1370,
 1373,
 1376,
 1399,
 1424,
 1427,
 1432,
 1460,
 1461,
 1465,
 1469,
 1471,
 1476,
 1490,
 1493,
 1504,
 1554,
 1555,
 1561,
 1567,
 1573,
 1585,
 1591,
 1619,
 1638,
 1657,
 1659,
 1666,
 1694,
 1699,
 1701,
 1703,
 1719,
 1725,
 1782,
 1788,
 1795,
 1816,
 1837,
 1869,
 1875,
 1876,
 1888,
 1963,
 1982,
 1988,
 1990,
 2014,
 2015,
 2020,
 2030,
 2044,
 2055,
 2090,
 2108,
 2113,
 2115,
 2116,
 2117,
 2123,
 2129,
 2134,
 2137,
 2148,
 2159,
 2166,
 2171,
 2210,
 2213,
 2229,
 2243,
 2251,
 2261,
 2271,
 2280

In [65]:
for x in reversed(ol):
    print(x)

4671
4652
4615
4599
4590
4575
4563
4558
4543
4514
4501
4495
4493
4487
4485
4478
4462
4452
4428
4398
4387
4381
4380
4334
4331
4326
4322
4295
4261
4244
4223
4182
4167
4133
4131
4128
4121
4120
4109
4060
4037
3976
3972
3967
3959
3951
3950
3900
3894
3867
3858
3831
3827
3798
3793
3786
3771
3764
3737
3725
3723
3706
3691
3647
3646
3645
3640
3636
3612
3610
3605
3588
3522
3508
3506
3467
3461
3444
3419
3402
3401
3384
3371
3369
3337
3333
3313
3294
3284
3264
3235
3231
3219
3205
3196
3189
3184
3174
3170
3121
3119
3103
3086
3070
3057
3056
3046
3033
3024
3019
3013
3011
2997
2986
2961
2945
2940
2936
2929
2913
2909
2907
2893
2878
2873
2871
2854
2818
2815
2814
2778
2762
2761
2753
2748
2745
2738
2735
2727
2722
2685
2683
2653
2629
2605
2593
2592
2591
2552
2544
2531
2485
2484
2422
2387
2375
2355
2292
2280
2271
2261
2251
2243
2229
2213
2210
2171
2166
2159
2148
2137
2134
2129
2123
2117
2116
2115
2113
2108
2090
2055
2044
2030
2020
2015
2014
1990
1988
1982
1963
1888
1876
1875
1869
1837
1816
1795
1788
1782
1725
